try {
	
	node
	{  		
		stage('clean-workspace') {
		    echo pwd
		    sh 'mvn --version'
		}
		stage('git-latest') {
		    echo 'Hello World'
		}
		stage('mvn-build') {
		    echo 'Hello World'
		}
		stage('mvn-junit') {
		    echo 'Hello World'
		}
		stage('mvn-sonar') {
		    echo 'Hello World'
		}
		stage('pcf-push'){
		    echo 'Hello World'
		}
	
	}
}
catch (e){
        echo "${e}"
}
