try {
	node{
		def workspace = env.WORKSPACE
		def sparseDir = 'demo/technology/microservices-pcf/migration/payment-use-case/microservices/pay-bank-beneficiary'
		stage('clean-workspace') {				
		echo "current working directory is : " 
		echo pwd
		
		echo "workspace directory is ${workspace}"
		echo "${sparseDir}"
		echo  "${sparseDir} >> ${workspace}/.git/info/sparse-checkout"
		//sh 'rm -rf ${workspace}/*'
			
		sh 'java -version' //working
		sh 'mvn --version' //working
	    
		maven 'mvn clean'
		echo "after maven clean"
		}
		stage('scm') {
		    echo 'scm sparse checkout3'
		    
		    echo "workspace directory is ${workspace}"
		
		    //def rtGradle = Artifactory.newMavenBuild()
		    
		    def config = [:]
		 
		    config.serviceRepo = 'git@ec2-54-84-120-131.compute-1.amazonaws.com:/home/git/ArchitectureTeam.git'
		    config.sparseCheckout= 'demo/technology/microservices-pcf/migration/payment-use-case/microservices/pay-bank-beneficiary'
		    config.gitBranch = 'master'	
		    //config.serviceRepo = 'https://github.com/rbhupesh/techinfo.git'
    		    //config.gitBranch = 'master'	
			
			
		    echo "check out branch ${config.gitBranch} from ${config.serviceRepo}"			
                    
		    git branch: config.gitBranch, url: config.serviceRepo //working step
			
		}
		stage('mvn-build') {
		    echo "mvn-build"
		    echo "workspace directory is ${workspace}"
		    echo "${sparseDir}"
		    echo '${workspace}/${sparseDir}'
		    sh "cd ${workspace}/${sparseDir}"
		    //maven 'mvn clean compile test package'
		    // Create an Artifactory Maven instance.
		    //def rtMaven = Artifactory.newMavenBuild()
		    //def buildInfo
		    //buildInfo = rtMaven.run pom: 'maven-example/pom.xml', goals: 'clean install'
		
		    echo "current working directory is : " 
		    sh "pwd"
		    sh "mvn -f  ${workspace}/${sparseDir}/pom.xml clean compile install"// running locally		    
		}
		stage('mvn-junit') {
		    echo 'mvn-junit'
		}
		stage('mvn-sonar') {
		    echo "mvn-sonar"
		    sh "mvn -f  ${workspace}/${sparseDir}/pom.xml sonar:sonar"// running locally
		}
		stage('pcf-push'){
		    echo 'pcf-push'
		
		sh "cd /var/lib/jenkins/workspace/PayBankBeneficiary/demo/technology/microservices-pcf/migration/payment-use-case/microservices/pay-bank-beneficiary"
                sh "cf login -a https://api.run.pivotal.io -u bhupesh.rathod@altimetrik.com -p Alti@123"
                sh "cf push -t 179"
			
			
		}
	
	}
}
catch (e){
	echo 'EXCEPTION OCCURED'
        echo "${e}"
}
